apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "CjJRMW1URWtkOHNlRWFCZmFmVVB4cll4N2ViWUJ1R0xQdlhOTnhEcHVDUjRjMjdYZ3VEM29KUVFK
OTlBTEFDWWVCakZYSjN3M0FBQUJBQ09HSWlxdA=="
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

